// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg4pVhPsMIruksLFGOD1oF8_G_RAKJtB4',
    appId: '1:752190036117:web:a70dba5404b1031bc2239c',
    messagingSenderId: '752190036117',
    projectId: 'flutter-todo-lab-1751d',
    authDomain: 'flutter-todo-lab-1751d.firebaseapp.com',
    storageBucket: 'flutter-todo-lab-1751d.appspot.com',
    measurementId: 'G-RK5G1ZPFCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JrFBOj6vvDZ7QRRH9xSKy1BUWVZ4zFI',
    appId: '1:752190036117:android:cb13d139182924ccc2239c',
    messagingSenderId: '752190036117',
    projectId: 'flutter-todo-lab-1751d',
    storageBucket: 'flutter-todo-lab-1751d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa3KZFug-jiL9t_xPjDx-uZUu5ilsrbbU',
    appId: '1:752190036117:ios:a81d9ad1976e81f3c2239c',
    messagingSenderId: '752190036117',
    projectId: 'flutter-todo-lab-1751d',
    storageBucket: 'flutter-todo-lab-1751d.appspot.com',
    iosBundleId: 'com.example.labTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa3KZFug-jiL9t_xPjDx-uZUu5ilsrbbU',
    appId: '1:752190036117:ios:a81d9ad1976e81f3c2239c',
    messagingSenderId: '752190036117',
    projectId: 'flutter-todo-lab-1751d',
    storageBucket: 'flutter-todo-lab-1751d.appspot.com',
    iosBundleId: 'com.example.labTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg4pVhPsMIruksLFGOD1oF8_G_RAKJtB4',
    appId: '1:752190036117:web:f763435befe59697c2239c',
    messagingSenderId: '752190036117',
    projectId: 'flutter-todo-lab-1751d',
    authDomain: 'flutter-todo-lab-1751d.firebaseapp.com',
    storageBucket: 'flutter-todo-lab-1751d.appspot.com',
    measurementId: 'G-T0GPJWK2J6',
  );
}
